### ISSUE TITLE
cannot import name Panel

### ISSUE THREAD

**Issue by ravi-ojha** [orf/django-debug-toolbar-template-timings#28]
Hi

I'm using `django-debug-toolbar-template-timings==0.6.6` with `django-debug-toolbar==1.5` on `django==1.4.2`. However, I'm getting `django.core.exceptions.ImproperlyConfigured: Error importing debug panel template_timings_panel.panels.TemplateTimings: "cannot import name Panel"` error. I could not find anything helpful on stackoverflow or other issues in this repo. Hence, creating a new issue.

Full traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 91, in inner_run
    self.validate(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name, True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/<APP_PATH>/plugins/debug_toolbar/models.py", line 30, in <module>
    load_panel_classes()
  File "/<APP_PATH>/plugins/debug_toolbar/toolbar/loader.py", line 99, in load_panel_classes
    (panel_module, e))
django.core.exceptions.ImproperlyConfigured: Error importing debug panel template_timings_panel.panels.TemplateTimings: "cannot import name Panel"
```

Can you figure what could be wrong?

Thanks
Ravi

**Comment by ravi-ojha** [comment]
It seems there we are using our own set of plugins. Closing this. Invalid.
