### ISSUE TITLE
AttributeError: 'module' object has no attribute 'generic_tag_compiler'

### ISSUE THREAD

**Issue by thenewguy** [orf/django-debug-toolbar-template-timings#29]
```
Django version 1.10.1, using settings 'project.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7f552b2eb398>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/apps.py", line 16, in ready
    dt_settings.check_middleware()
  File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/settings.py", line 173, in check_middleware
    from debug_toolbar.middleware import DebugToolbarMiddleware
  File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/middleware.py", line 16, in <module>
    from debug_toolbar.toolbar import DebugToolbar
  File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/toolbar.py", line 151, in <module>
    urlpatterns = DebugToolbar.get_urls()
  File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/toolbar.py", line 145, in get_urls
    for panel_class in cls.get_panel_classes():
  File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/toolbar.py", line 118, in get_panel_classes
    mod = import_module(panel_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/template_timings_panel/panels/TemplateTimings.py", line 91, in <module>
    template_base.generic_tag_compiler)
AttributeError: 'module' object has no attribute 'generic_tag_compiler'
```

**Comment by thenewguy** [comment]
Not sure what information is important to you or if Django 1.10 is supposed to work.  I am using django templates with the cached loader

**Comment by strokirk** [comment]
This is probably a duplicate of #24 , which was fixed in #27 .

@orf , could you release this fix to PyPi?

**Comment by orf** [comment]
Ok, I've done a release, let me know if it works :+1: 

Sorry about the horribly late response time.
